name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 17
    - name: Run unit tests
      run: ./gradlew test
    - name: Determine coverage
      run: ./gradlew jacocoTestReport
    - name: Scan with Sonar
      run: ./gradlew sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Build with Gradle
      run: ./gradlew build
